### ISSUE TITLE
Zuschnitt Nistkasten pdf

### ISSUE THREAD

**Issue by noworrries** [MakeMagazinDE/Nistkasten-V2#5]
Maße für die Bodenplatte und Front sind durch einen Zahlendreher zu klein.

Breite Rückwand - 2 x Plattendicke ist 164mm, nicht 146mm

Wer blindlings sägt, sägt 2x.

**Comment by cyrix2000** [comment]
Die Plattendicke ist doch 12mm, 170mm - 2x12mm = 146mm. Das stimmt dann doch eigentlich, oder?

**Comment by noworrries** [comment]
Bei mir im Printartikel wurden 3 mm gedruckt... auch wenn ich für meine eigene Planung 10-12 mm annahm.

OK hatte das Sperrholz 3mm als Außenwand interpretiert, als ich auf der Zeichnung keine Stärke gefunden hatte und schnell bei der Materialliste geschaut habe. 
Die Siebdruckplatte hatte ich gar nicht gesehen... 
der identische Verweis auf die „Download-Zeichnung“ tat das übrige. 
Zusammen mit 170-(2x3) = 164 ...

Hast recht.

Gruß 
Flo

**Comment by cyrix2000** [comment]
Ich habe eine CAD Datei (step) fuer die Holzelemente erstellt und per fork (plus pull request) hochgeladen.
